POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "email": "mohan123@gmail.com",
  "password": "password-1",
  "userName": "Prasant",
  "address": "200 Grasmere street"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "mohan123@gmail.com",
  "password": "password-1"
}

###

PUT http://localhost:3000/api/admin
Content-Type: application/json

{
  "electricityDay" : 0.34,
  "electricityNight": 0.2,
  "gas": 0.1,
  "standingCharge": 0.74
}

###

POST http://localhost:3000/api/dashboard
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzI0MDI1NTEsImV4cCI6MTY3MjQ4ODk1MX0._K865TVn0l0Wguv0E1-SwVSRT7hiuJ8x2ONFsWVkXr4

{
  "email": "mohan123@gmail.com",
  "submissionDate": "2022-11-28T00:00:00.000Z",
  "dayReading": 200,
  "nightReading": 500,
  "gasReading": 1600
}

###
GET http://localhost:3000/api/login
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzIzMjY1MDAsImV4cCI6MTY3MjQxMjkwMH0.KxxqJmOGHvudxRcry37o6-UTkI4DDbuZej4TAePN5Ys


###
GET http://localhost:3000/api/dashboard
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzI0MDI1NTEsImV4cCI6MTY3MjQ4ODk1MX0._K865TVn0l0Wguv0E1-SwVSRT7hiuJ8x2ONFsWVkXr4