POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "email": "mohan123@gmail.com",
  "password": "password-1",
  "userName": "Prasant",
  "address": "200 Grasmere street"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "mohan123@gmail.com",
  "password": "password-1"
}

###

PUT http://localhost:3000/api/admin
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2FjMDUxNzlhMjY1ZTE5OGUwOTE4NzciLCJpYXQiOjE2NzI3NzYyNjAsImV4cCI6MTY3Mjg2MjY2MH0.52g7GRMFOnaGubsa61-hF5ubq-0hly1gjDctv42SE6A

{
  "electricityDay" : 0.34,
  "electricityNight": 0.2,
  "gas": 0.1,
  "standingCharge": 0.74
}

###

POST http://localhost:3000/api/dashboard
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzI3ODQxMjksImV4cCI6MTY3Mjg3MDUyOX0.2ISUeJib46fmdRuDOQbzG6R973WafsTMFcrjsc25cxc

{
  "email": "mohan123@gmail.com",
  "submissionDate": "2022-12-28T00:00:00.000Z",
  "dayReading": 400,
  "nightReading": 850,
  "gasReading": 2500
}

###
GET http://localhost:3000/api/login
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzIzMjY1MDAsImV4cCI6MTY3MjQxMjkwMH0.KxxqJmOGHvudxRcry37o6-UTkI4DDbuZej4TAePN5Ys


###
GET http://localhost:3000/api/dashboard
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzI0MDI1NTEsImV4cCI6MTY3MjQ4ODk1MX0._K865TVn0l0Wguv0E1-SwVSRT7hiuJ8x2ONFsWVkXr4


###
POST http://localhost:3000/api/customer
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzI0ODUyMjgsImV4cCI6MTY3MjU3MTYyOH0.n8Z-fY5Fg8468sOOzQiWKSoL-qQRgctu-tuavPu-L10

{
  "email": "mohan123@gmail.com",
  "currentBalance": 200,
  "voucherCode":"XA35GJ9T"
}

###
PUT http://localhost:3000/api/customer
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2E4MGFmNzRiM2EyNThhYTQwYmE3NzEiLCJpYXQiOjE2NzI0ODUyMjgsImV4cCI6MTY3MjU3MTYyOH0.n8Z-fY5Fg8468sOOzQiWKSoL-qQRgctu-tuavPu-L10

{
  "email": "mohan123@gmail.com",
  "currentBalance": 414
}

### Admin login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "gse@shangrila.gov.un",
  "password": "gse@energy"
}

###
GET http://localhost:3000/api/admin
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2FjMDUxNzlhMjY1ZTE5OGUwOTE4NzciLCJpYXQiOjE2NzI3NzYyNjAsImV4cCI6MTY3Mjg2MjY2MH0.52g7GRMFOnaGubsa61-hF5ubq-0hly1gjDctv42SE6A